-- TABLE: teams
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    logo_url TEXT
);

-- TABLE: players
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id), -- Linked to Team
    name TEXT NOT NULL,
    role TEXT, -- 'Batsman', 'Bowler', 'All-Rounder', 'Wicketkeeper'
    batting_style TEXT,
    bowling_style TEXT,
    runs INTEGER DEFAULT 0,
    balls INTEGER DEFAULT 0,
    fours INTEGER DEFAULT 0,
    sixes INTEGER DEFAULT 0,
    is_out BOOLEAN DEFAULT FALSE,
    details TEXT
);

-- TABLE: matches
-- Added current_bowler_id
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name_batting TEXT DEFAULT 'Home Team',
    team_name_bowling TEXT DEFAULT 'Away Team',
    team_score INTEGER DEFAULT 0,
    wickets INTEGER DEFAULT 0,
    overs INTEGER DEFAULT 0,
    balls INTEGER DEFAULT 0, -- Valid balls in current over
    current_striker_id BIGINT REFERENCES players(id),
    non_striker_id BIGINT REFERENCES players(id),
    current_bowler_id BIGINT REFERENCES players(id) -- NEW
);

-- TABLE: match_squads
CREATE TABLE match_squads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id),
    player_id BIGINT REFERENCES players(id),
    is_playing_11 BOOLEAN DEFAULT FALSE
);

-- TABLE: balls (The Source of Truth)
CREATE TABLE balls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id),
    inning_no INTEGER DEFAULT 1,
    over_no INTEGER,      -- Current over number (e.g. 5)
    ball_no INTEGER,      -- Valid ball number in over (e.g. 3) or delivery count
    striker_id BIGINT REFERENCES players(id),
    non_striker_id BIGINT REFERENCES players(id),
    bowler_id BIGINT REFERENCES players(id),
    runs_off_bat INTEGER DEFAULT 0,
    extras INTEGER DEFAULT 0, -- Wide/No Ball counts as extra run
    extra_type TEXT, -- 'wide', 'noball', 'bye', 'leg-bye'
    is_four BOOLEAN DEFAULT FALSE,
    is_six BOOLEAN DEFAULT FALSE,
    is_wicket BOOLEAN DEFAULT FALSE,
    action_type TEXT, -- 'run', 'wide', 'noball', 'bye', 'leg-bye', 'wicket'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TABLE: wickets
CREATE TABLE wickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ball_id BIGINT REFERENCES balls(id),
    player_out_id BIGINT REFERENCES players(id),
    wicket_type TEXT, -- Caught, Bowled, etc.
    fielder_id BIGINT REFERENCES players(id),
    score_at_dismissal TEXT -- e.g. "145/3"
);

-- 1. Create the Tournaments Table (for the "Edit Tournament Info" screen)
CREATE TABLE tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    status TEXT DEFAULT 'upcoming', -- upcoming, active, completed
    logo_url TEXT
);

-- 2. Create the Commentary Table (For your future feature)
CREATE TABLE commentary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id),
    inning INTEGER DEFAULT 1,
    over_number NUMERIC(4,1), -- e.g. 1.4
    ball_id BIGINT REFERENCES balls(id),
    text TEXT, -- "Four runs! Beautiful shot."
    event_type TEXT, -- run, wicket, boundary, extra
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Upgrade the Matches Table (The Critical Step)
-- We are adding columns to support the "New Match Settings" popup
ALTER TABLE matches 
ADD COLUMN tournament_id BIGINT REFERENCES tournaments(id),
ADD COLUMN team_a_id BIGINT REFERENCES teams(id),
ADD COLUMN team_b_id BIGINT REFERENCES teams(id),
ADD COLUMN match_date DATE,
ADD COLUMN start_time TIME,
ADD COLUMN status TEXT DEFAULT 'scheduled', -- scheduled, live, completed
ADD COLUMN toss_winner_id BIGINT REFERENCES teams(id),
ADD COLUMN toss_decision TEXT, -- 'bat' or 'bowl'
ADD COLUMN current_inning INTEGER DEFAULT 1, -- Crucial for Second Innings
ADD COLUMN target_score INTEGER DEFAULT 0,   -- Crucial for Second Innings
ADD COLUMN team_batting_id BIGINT REFERENCES teams(id),
ADD COLUMN team_bowling_id BIGINT REFERENCES teams(id);
